### ISSUE TITLE
Importing of missing element not working

### ISSUE THREAD

**Issue by vedtam** [runem/vscode-lit-plugin#12]
Hi,

Thanks for this nice plugin! I've tried to import a "suggested" missing element but as I click on the element's name in the import popup, nothing happens:

![issue (1)](https://user-images.githubusercontent.com/4981592/55665487-51d0b500-5849-11e9-973f-45f9f02c2edc.gif)

code: 1.32.3
lit-element: ^2.1.0

Any idea?
Thanks.

**Comment by runem** [comment]
Hi, I'm happy that you like the plugin :-)

Thanks for creating an issue. In the gif it seems like it's the "autocompletion feature" and not the "suggested fix feature" that pops up. You should find a popup with the text `Import "fch-channel-manager" from module "./..."` like in the gif below where I first show autocompletion and then suggested fix.

![import](https://user-images.githubusercontent.com/5372940/55683759-a22c3d80-5943-11e9-9acf-04fd62c25d1f.gif)

**Comment by vedtam** [comment]
Aaa indeed, thanks! And say (1.) if the element is imported dynamically in another file, I guess there is no way to ignore the check for this particular import but to disable the check globally using 'skipMissingImports'? And (2.) while the import happens the path is wrapped in double quotes but my project uses single quotes, can this be changed?

Thanks!

**Comment by runem** [comment]
Great points! 

Regarding (1.) Right now dynamic imports counts as making the component available in the entire file because more granular analysis is very difficult for those. It also makes the components imported available in dependent files. (eg. a component will become `imported` in file `A` if file `A` depends on file `B` and the component is dynamically imported in file `B`). I'm wondering if I should change the default behavior to make it available in the entire file, but not files depending on it. And if I in addition should add an option to the configuration controlling this behavior. What do you think?

Regarding (2.) Great idea! I created an issue on it here #14

**Comment by vedtam** [comment]
Hi,

Thanks for the feedback. My use case for dynamic imports is a bit "unusual", actually I control what gets imported using a custom router (inside app.ts) when the url changes:

```
const handleClientRoutes = async (route: Route, dispatch: ThunkDispatch<RootState, undefined, RootActions>) => {
  switch (route[1]) {
    ...
    case 'channel-manager':
      await import('../components/client/fch-channel-manager.js');
      break;
    default:
      route[0] = '404';
  }
};
```

So `fch-channel-manager.ts` doesn't depend on app.ts or vice versa (like in the case of A and B as you mentioned) so making the import available in the entire file (project) would solve my issue but don't know if this applies to others as well, so yes configuring this / user would be probably the best thing, _I guess_.

**Comment by runem** [comment]
I think in your case you should go with `skipMissingImports`. I will soon be refactoring the module dependency analyzer, and then I will try to think your use case into my considerations :-) 

I will close this issue for now, thanks for your suggestions!
