### ISSUE TITLE
Native `input` error: " Type 'string' is not assignable to '"hidden" | "text" | "search" | ..."

### ISSUE THREAD

**Issue by vedtam** [runem/vscode-lit-plugin#15]
Hi,

lit-plugin complains when binding a string value to the type attribute:

![Screen Shot 2019-05-02 at 07 58 15](https://user-images.githubusercontent.com/4981592/57057317-679e9200-6cb0-11e9-96c2-85e5cd85b8cf.png)

Any suggestion?
Thanks.

**Comment by runem** [comment]
Hi, thanks for opening an issue!

I think this is expected behavior because Typescript expects a string literal and not just any string here. For example Typescript will complain when assigning `str` to `color` here:
```typescript
const str: string = "not a color";
const color: "red" | "green" | "blue" = str;
```

I have two suggestions for what you can do:

a. You can cast the value to `any` in the assignment.
```typescript
<input type="${type as any}" ...>
```

b. You can specify the type of the "type" property to be `"hidden" | "text" | "search" | ...` which can of course be refactored into a type alias :-) 
```typescript
@property({type: String})
type: "hidden" | "text" | "search" | ... = "text";
```
