### ISSUE TITLE
Using lit-plugin with Polymer

### ISSUE THREAD

**Issue by herberthobregon** [runem/vscode-lit-plugin#19]
I have a question, can you use this plugin with `Polymer`?
I'm working on a new project and everything is in `Typescript` and `Litelement` and this plugin **works great**!

But I have another project where `Polymer and LitElement` are mixed and for some reason, the plugin doesn't work. 

If it were the case, I can send you the complete source of project so you can try it and see why it does not work in the html templates

Even in the elements that are pure (litElement) it stops working.
I am not an expert in VS Code extensions but if I can debug my machine, let me know

And thank you very much for this FANTASTIC plugin!

**Comment by runem** [comment]
Hi Herberth, thank you so much for opening an issue! :-) I'm happy you like the extension, and I'm sorry for the hiccup you experienced!

Right now [web-component-analyzer](https://github.com/runem/web-component-analyzer) does the job of analyzing components, but I haven't yet implemented full support for Polymer web components. In addition it's still missing support for mixins, but I will soon be implementing that feature (see issue https://github.com/runem/web-component-analyzer/issues/33).

I'm curious on two things:
  1. How do your Polymer components look?
  2. What specific error/component makes the plugin crash?

It would be really helpful if you could share the source code with me, then I would be able to debug both things. You could simply send it as a zip-file to my email: runemehlsen@gmail.com. Alternatively I can give you some directions on how to debug the extension yourself.

**Comment by herberthobregon** [comment]
I thank you for the quick response!

I sent you the source code (take care, please 😂)

Basically, things like
⌘ + click on the custom elements
Attribute / property type checking
📣 Report missing imports of custom elements
⚡️Event checking
📬 Slot checking
🚶Goto definition
✏️ Code completions for css and html

And Polymer components looks like a:
```js
import {C2Element, html} from '@c2_comp/c2-element/c2-element.js';
import '@conectate/ct-button/ct-button';

// C2Element extends PolymerElement
class SubscribeBlock extends C2Element {
    static get template() {
        return html`
<style>
    :host {
        display: flex;
        width: 100%;
        background: var(--app-grad);
        color: #fff;
        padding: 16px 0;
    }
    .description {
        font-size: 24px;
        line-height: 1.5;
        margin: 0 0 16px;
    }
    ct-button {
        color: #fff;
        border-radius: 3rem;
        border-color: white;
    }
    a {
        display: block;
        max-width: 900px;
        margin: 0 auto;
        width: 100%;
        text-align: center;
    }
</style>
<div class="container" layout vertical center$="[[viewport.isTabletPlus]]">
    <div class="description">Find US</div>
    <a href="[[strings.suscribe_link]]" target="_blank">
        <ct-button class="animated icon-right"
                      disabled$="[[subscribed]]"
                      on-tap="_subscribe">{{strings.suscribe}}
        </ct-button>
    </a>
</div>
        `;
    }
}
window.customElements.define('subscribe-block', SubscribeBlock);
```
If I can help you to do a debugging, you can tell me how to do it and if I can help something, you can let me know

**Comment by runem** [comment]
Thank you so much for sending me the code. I have started looking into the matter.

The crash seems to be a result of 
 * Line 101, 129, 148, 168, 193, 213, 236, 347 in `c2_comp/@herberthobregon/google-chart/google-chart.js`. 
 * Line 16, 129 in `c2_comp/@herberthobregon/google-chart/google-chart-loader.js`

Specifically, these lines of JSDoc resulted in the jsdoc parser crashing.

I have already fixed it in `web-component-analyzer`, and the fix will get out when I publish a new version of it. For now you can simply delete the lines (or remove the exclamation sign on each line), and the plugin shouldn't crash anymore. In addition I will look into making the plugin more resilient, - a line of JSDoc shouldn't crash the entire plugin :-) 

When the plugin was working fine again, I found that Custom CSS Mixins (`@apply ...` lines `<style>` tags) result in a lot of warnings because it expects raw CSS here.  To fix this I'm thinking of introducing an extension-setting to tell it if you are using CSS or SASS.

Tomorrow, I will look into Polymer specific component syntax and create a corresponding issue at `web-component-analyzer`. To be clear, I do not plan on implementing support for Polymer specific templating syntax, but plan on making it possible to consume Polymer components correctly in lit-html templates.

**Comment by herberthobregon** [comment]
Wow! thanks! This has helped me a lot!
now all the features of the plugin work!

I've eliminated @apply (I think it's a bad practice and it's not native nor is it a standard)

Totally agree, Polymer is not worth investing so much time but any improvement is welcome!
The syntax is basically the same

in LitElement
html`<div @click=${this.funct}" @custom-event=${this.fo}>${this.myProp}</div>`

in Polymer maybe
html`<div on-click="funct">{{myProp}}</div>`
html`<div on-custom-event="fo">[[myProp]]</div>`

Thank you very much for the excellent work!

**Comment by runem** [comment]
No problems, I'm happy to help! :-)
